name: Hello Workflow
on:
  push:
    branches:
      - main
jobs:
   say-hello:
     runs-on: ubuntu-latest
     steps:
       - name: Print greeting
         run: echo "hello Devops student for sunday class!!!"