name: Hello Workflow
on:
  push:
    branches:
      - main
jobs:
   say-hello:
     runs-on: ubuntu-latest
     steps:
       - name: Step 1 - Greet
         run: echo "Hello from step 1"
       - name: Step 2 - Show current directory
         run: pwd
       - name: Step 3 - List files
         run: ls -la